namespace GooseDesktopPet;

public enum PetSegmentationBackend
{
    None,
    External,
    GrabCut,
    Rembg,
    CustomModel
}

public sealed record PetImportOptions(
    PetSegmentationBackend SegmentationBackend,
    bool NormalizePosition,
    bool NormalizeScale,
    IReadOnlySet<string> PreserveYStates,
    IReadOnlySet<string> FlipStates,
    IReadOnlySet<string> StabilizeMarkerXStates,
    IReadOnlyDictionary<string, int> TrimLeadingFrames);

public sealed record PetImportResult(
    string ManifestPath,
    IReadOnlyList<string> StateNames,
    int CanvasWidth,
    int CanvasHeight);

public interface IPetSegmentationService
{
    Task SegmentAsync(string sourceVideoPath, string outputVideoOrFramesPath, CancellationToken cancellationToken);
}

public interface IPetAssetImporter
{
    Task<PetImportResult> ImportAsync(
        IReadOnlyList<string> sourceVideoPaths,
        string outputDirectory,
        PetImportOptions options,
        CancellationToken cancellationToken);
}

public sealed class ExternalPetAssetImporter : IPetAssetImporter
{
    public Task<PetImportResult> ImportAsync(
        IReadOnlyList<string> sourceVideoPaths,
        string outputDirectory,
        PetImportOptions options,
        CancellationToken cancellationToken)
    {
        // Reserved for the user-facing replacement flow.
        // The current prototype consumes a prepared manifest generated by scripts/import_transparent_webm.py.
        // Future implementations can wrap that script, a bundled FFmpeg pipeline, or a remote AI matting service.
        throw new NotImplementedException("Character replacement import flow is reserved for a later build.");
    }
}
