using System.Diagnostics;

namespace GooseDesktopPet;

public enum PetSegmentationBackend
{
    None,
    External,
    GrabCut,
    Rembg,
    RobustVideoMatting,
    CustomModel
}

public sealed record PetImportOptions(
    PetSegmentationBackend SegmentationBackend,
    bool NormalizePosition,
    bool NormalizeScale,
    IReadOnlySet<string> PreserveYStates,
    IReadOnlySet<string> FlipStates,
    IReadOnlySet<string> StabilizeMarkerXStates,
    IReadOnlyDictionary<string, int> TrimLeadingFrames);

public sealed record PetImportResult(
    string ManifestPath,
    IReadOnlyList<string> StateNames,
    int CanvasWidth,
    int CanvasHeight);

public interface IPetSegmentationService
{
    Task SegmentAsync(string sourceVideoPath, string outputVideoOrFramesPath, CancellationToken cancellationToken);
}

public sealed record ExternalPetToolPlugin(
    string Id,
    PetSegmentationBackend Backend,
    string ExecutablePath,
    string ArgumentsTemplate,
    string WorkingDirectory);

public sealed class ExternalProcessSegmentationService(ExternalPetToolPlugin plugin) : IPetSegmentationService
{
    public async Task SegmentAsync(
        string sourceVideoPath,
        string outputVideoOrFramesPath,
        CancellationToken cancellationToken)
    {
        var arguments = plugin.ArgumentsTemplate
            .Replace("{input}", Quote(sourceVideoPath), StringComparison.OrdinalIgnoreCase)
            .Replace("{output}", Quote(outputVideoOrFramesPath), StringComparison.OrdinalIgnoreCase);

        var startInfo = new ProcessStartInfo
        {
            FileName = plugin.ExecutablePath,
            Arguments = arguments,
            WorkingDirectory = plugin.WorkingDirectory,
            UseShellExecute = false,
            CreateNoWindow = true,
            RedirectStandardError = true,
            RedirectStandardOutput = true
        };

        using var process = Process.Start(startInfo)
            ?? throw new InvalidOperationException($"Could not start pet tool plugin: {plugin.Id}");

        var stdoutTask = process.StandardOutput.ReadToEndAsync(cancellationToken);
        var stderrTask = process.StandardError.ReadToEndAsync(cancellationToken);
        await process.WaitForExitAsync(cancellationToken);

        if (process.ExitCode != 0)
        {
            var stdout = await stdoutTask;
            var stderr = await stderrTask;
            throw new InvalidOperationException(
                $"Pet tool plugin '{plugin.Id}' failed with exit code {process.ExitCode}.\n{stdout}\n{stderr}");
        }
    }

    private static string Quote(string value)
    {
        return "\"" + value.Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";
    }
}

public interface IPetAssetImporter
{
    Task<PetImportResult> ImportAsync(
        IReadOnlyList<string> sourceVideoPaths,
        string outputDirectory,
        PetImportOptions options,
        CancellationToken cancellationToken);
}

public sealed class ExternalPetAssetImporter : IPetAssetImporter
{
    public Task<PetImportResult> ImportAsync(
        IReadOnlyList<string> sourceVideoPaths,
        string outputDirectory,
        PetImportOptions options,
        CancellationToken cancellationToken)
    {
        // Reserved for the user-facing replacement flow.
        // The current prototype consumes a prepared manifest generated by scripts/import_transparent_webm.py.
        // Future implementations can wrap that script, a bundled FFmpeg pipeline, or a remote AI matting service.
        throw new NotImplementedException("Character replacement import flow is reserved for a later build.");
    }
}
